version: "3.7"

services:
  core:
    build:
      context: .
      args:
        - core_queue=main
        - rmq_connect=amqp://guest:guest@localhost:5672
      network: host
    command: 'python /root/run.py -c /root/worker.cfg -l /root/logs/log.log'
    volumes:
    - /root/idls/logs:/root/logs
    container_name: core_service
    network_mode: host
    restart: always
