version: "3.7"

services:
  backend:
    build:
      context: .
      network: host
    image: backend:latest
    container_name: biogen-backend
    environment:
    - NODE_ENV=production
    env_file:
    - ./env.env
    network_mode: host
    restart: always
