version: "3"

services:
  rabbitmq:
    hostname: localhost
    container_name: rabbitmq
    image: rabbitmq:3.7.14-management
    ports:
    - 5672:5672
    - 15672:15672
    volumes:
    - /root/localhost-rabbitmq:/var/lib/rabbitmq
    restart: always

